# Generated by Django 3.2.5 on 2021-07-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_auto_20210530_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='shor_name',
            field=models.CharField(max_length=20, verbose_name='Nombre Corto'),
        ),
    ]
