# Generated by Django 3.2.3 on 2021-05-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='deaprtamento',
            new_name='departamento',
        ),
    ]
