# Generated by Django 3.2.5 on 2021-07-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_remove_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(null=True, to='persona.Habilidades'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'CONTADOR'), ('1', 'ADMINISTRADOR'), ('2', 'ECONOMISTA'), ('3', 'OTRO')], max_length=1, null=True, verbose_name='Trabajo'),
        ),
    ]
