# Generated by Django 3.2.5 on 2021-07-21 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_auto_20210720_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='job',
        ),
        migrations.DeleteModel(
            name='Habilidades',
        ),
    ]
